export const productRoutes = [
  ["aniline", "Aniline", "62-53-3", "Amines"],
  ["cyclohexanone", "Cyclohexanone", "108-94-1", "Ketones"],
  ["dimethylformamide-dmf", "Dimethylformamide (DMF)", "68-12-2", "Amides"],
  ["glacial-acetic-acid-gaa", "Glacial Acetic Acid (GAA)", "64-19-7", "Organic Acids"],
  ["methylene-chloride-dcm", "Methylene Chloride (DCM)", "75-09-2", "Chlorinated Solvents"],
  ["trichloromethane-tcm", "Trichloromethane (Chloroform)", "67-66-3", "Chlorinated Solvents"],
  ["trichloroethylene-tce", "Trichloroethylene (TCE)", "79-01-6", "Chlorinated Solvents"],
  ["perchloroethylene-pce", "Perchloroethylene (PCE)", "127-18-4", "Chlorinated Solvents"],
  ["monoethanolamine-mea", "Monoethanolamine (MEA)", "141-43-5", "Amines"],
  ["diethanolamine-dea", "Diethanolamine (DEA)", "111-42-2", "Amines"],
  ["furfuryl-alcohol", "Furfuryl Alcohol", "98-00-0", "Alcohols"],
  ["toluene-diisocyanate-20-80-tdi-20-80", "Toluene Diisocyanate 80/20 (TDI)", "584-84-9", "Isocyanates"],
  ["propylene-glycol-pg", "Propylene Glycol (PG)", "57-55-6", "Alcohols"],
  ["2-ethylhexanol-2eh", "2-Ethylhexanol (2-EH)", "104-76-7", "Alcohols"],
  ["n-butanol-nba", "N-Butanol (NBA)", "71-36-3", "Alcohols"],
  ["dimethyl-carbonate-dmc", "Dimethyl Carbonate (DMC)", "616-38-6", "Carbonates"],
  ["formic-acid-85", "Formic Acid 85%", "64-18-6", "Organic Acids"],
  ["propionic-acid-pa", "Propionic Acid", "79-09-4", "Organic Acids"],
  ["acrylic-acid-aa", "Acrylic Acid", "79-10-7", "Organic Acids"],
  ["methacrylic-acid-maa", "Methacrylic Acid", "79-41-4", "Organic Acids"],
  ["styrene-sm", "Styrene Monomer", "100-42-5", "Chemical Intermediates"],
  ["phenol", "Phenol", "108-95-2", "Chemical Intermediates"],
  ["1-2-dichloroethane-edc", "1,2-Dichloroethane (EDC)", "107-06-2", "Chlorinated Solvents"],
  ["methanol", "Methanol", "67-56-1", "Alcohols"],
  ["toluene-tol", "Toluene", "108-88-3", "Aromatic Solvents"],
  ["acetone-ac", "Acetone", "67-64-1", "Ketones"],
  ["epichlorohydrin-ech", "Epichlorohydrin (ECH)", "106-89-8", "Chemical Intermediates"],
  ["vinyl-acetate-monomer-vam", "Vinyl Acetate Monomer (VAM)", "108-05-4", "Chemical Intermediates"],
  ["1-4-butanediol-bdo", "1,4-Butanediol (BDO)", "110-63-4", "Alcohols"],
  ["butyl-cellosolve-bcs", "Butyl Cellosolve (BCS)", "111-76-2", "Glycol Ethers"],
  ["isobutanol-iba", "Isobutanol (IBA)", "78-83-1", "Alcohols"],
  ["methylcyclohexane-mch", "Methylcyclohexane (MCH)", "108-87-2", "Hydrocarbon Solvents"],
  ["triethylamine-tea", "Triethylamine (TEA)", "121-44-8", "Amines"],
  ["xylene", "Xylene", "1330-20-7", "Aromatic Solvents"],
].map(([slug, name, cas, category]) => ({ slug, name, cas, category }));

export const insightRoutes = [
  "how-to-export-dichloromethane-from-china",
  "one-stop-chemical-export-compliance-services-from-china",
  "inland-port-chemical-export-services-china",
  "dongying-strategic-gateway-chemical-exports-china",
  "factory-to-port-chemical-export-compliance-workflow-china",
  "how-to-export-dangerous-goods-from-china",
  "dimethyl-carbonate-supplier-china-export-guide",
  "dimethyl-carbonate-vietnam-china-supplier-guide",
  "methylene-chloride-india-dcm-msds-china-supply-guide",
];

