import { useState } from "react";
import type { FormEvent } from "react";
import type { Article, Lang, Page, Product } from "./HomePage";
import "./HomePageApproved.css";

type Props={go:(page:Page)=>void;lang:Lang;products:Product[];articles:Article[];onOpenArticle:(slug:string)=>void};
const copy={
  en:{nav:["Home","Chemical Sourcing","Export Support","Products","Shandong Supply Base","Insights","About","Contact"],hero:"China Chemical Sourcing & Export Support",intro:"Work directly with an independent coordinator connected to Shandong’s petrochemical supply base and qualified resources for repacking, inspection, DG documentation, customs and shipping.",based:"Based in Shandong, China · Supporting international industrial buyers"},
  zh:{nav:["首页","化工品寻源","出口支持","产品","山东产业带","行业洞察","关于","联系"],hero:"中国化工品寻源与出口支持",intro:"直接对接立足山东的独立协调人，连接石化产业带货源，以及分装、检验、危包单证、报关和订舱等合格服务资源。",based:"立足中国山东 · 服务国际工业采购商"}
};
const routes:Page[]=["home","chemical-sourcing","export-support","products","shandong-supply-base","insights","about","contact"];
const safe=(v:{en:string;zh:string},lang:Lang)=>v?.[lang]||v?.en||"";
function slug(p:Product){return p.name.en.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
const showcase=[
 {label:"Xylene",cas:"1330-20-7",image:"/home-v5/xylene.webp",text:"Solvent sourcing, specification and drum or ISO tank review."},
 {label:"Methylene Chloride",cas:"75-09-2",image:"/home-v5/methylene-chloride.webp",text:"Supplier, COA, MSDS, packing and DG shipment review."},
 {label:"Chloroform",cas:"67-66-3",image:"/home-v5/chloroform.webp",text:"Industrial-use, destination and export eligibility review."},
 {label:"Aniline",cas:"62-53-3",image:"/home-v5/aniline.webp",text:"Specification, packing and DG export coordination."},
 {label:"Dimethyl Carbonate",cas:"616-38-6",image:"/home-v5/dimethyl-carbonate.webp",text:"Grade, application and shipment-option confirmation."},
 {label:"Acetone",cas:"67-64-1",image:"/home-v5/acetone.webp",text:"Industrial packing and export-document review."}
];
function openProduct(p:Product){history.pushState({},"",`/products/${slug(p)}`);dispatchEvent(new PopStateEvent("popstate"));scrollTo({top:0,behavior:"smooth"})}
const Icon=({children}:{children:string})=><span className="ah-icon" aria-hidden="true">{children}</span>;

export default function HomePageApproved({go,lang,products,articles,onOpenArticle}:Props){
 const [menu,setMenu]=useState(false);const [status,setStatus]=useState("");const c=copy[lang];
 const guides=articles.slice(0,3);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus(lang==="zh"?"正在提交…":"Sending…");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch("/api/inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error();setStatus(lang==="zh"?"已收到需求，我会直接回复。":"Requirement received. I will reply directly.");form.reset()}catch{setStatus(lang==="zh"?"暂时无法提交，请使用邮件或 WhatsApp。":"Unable to send. Please use email or WhatsApp.")}}
 return <main className="approved-home">
  <header className="ah-header"><div className="ah-shell ah-header-inner"><button className="ah-brand" onClick={()=>go("home")}><b>ChinaChemExport</b><small>Independent Chemical Sourcing &amp; Export Coordinator</small></button><button className="ah-menu" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""}>{c.nav.map((n,i)=><button className={i===0?"active":""} key={`${n}-${i}`} onClick={()=>go(routes[i])}>{n}</button>)}<button className="ah-top-cta" onClick={()=>go("contact")}>{lang==="zh"?"沟通采购需求":"Discuss Your Requirement"} →</button></nav></div></header>
  <section className="ah-hero"><div className="ah-hero-bg"/><div className="ah-shell ah-hero-content"><div><h1>{c.hero}</h1><p>{c.intro}</p><strong>{c.based}</strong><div className="ah-actions"><button className="primary" onClick={()=>go("contact")}>{lang==="zh"?"沟通采购需求":"Discuss Your Requirement"} →</button><button className="secondary" onClick={()=>go("export-support")}>{lang==="zh"?"了解寻源流程":"How Sourcing Works"}</button></div></div><div className="ah-hero-route" aria-hidden="true"><span>▧<small>Repacking<br/>&amp; Inspection</small></span><i>›</i><span>▤<small>DG Documents</small></span><i>›</i><span>♟<small>Customs<br/>Declaration</small></span><i>›</i><span>▰<small>Vessel Booking<br/>&amp; Shipping</small></span></div></div></section>
  <section className="ah-capabilities"><div className="ah-shell ah-cap-grid">{[["▥","Regional Chemical Supply","Access to Chinese chemical suppliers in Shandong and nearby regions."],["●","Competitive Sourcing Options","Multiple qualified suppliers for specification and price confirmation."],["◇","Qualified Repacking Support","Export packing and labelling arranged through qualified local resources."],["▰","Export Process Coordination","Customs declaration, vessel booking and shipment follow-up with approved providers."]].map(x=><article key={x[1]}><Icon>{x[0]}</Icon><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="ah-section"><div className="ah-shell"><div className="ah-section-title"><div><h2>From Requirement to Shipment</h2><p>I turn a buyer’s product requirement into a reviewed supply and export plan.</p></div><button onClick={()=>go("export-support")}>View the complete chemical export support process →</button></div><div className="ah-steps">{[["1","▤","Define Requirement","Product, CAS, specification, quantity, packing and destination."],["2","⌕","Confirm Supply Solution","Supplier, current availability, commercial terms and batch documents."],["3","◇","Prepare for Export","Qualified repacking, labels, inspection and DG packaging documents."],["4","▰","Coordinate Shipment","Customs declaration, vessel booking, DG transport and port follow-up."]].map((x,i)=><article key={x[0]}><b>{x[0]}</b><Icon>{x[1]}</Icon><div><h3>{x[2]}</h3><p>{x[3]}</p></div>{i<3&&<i>›</i>}</article>)}</div></div></section>
  <section className="ah-section ah-products"><div className="ah-shell"><div className="ah-section-title"><div><h2>Selected Chemicals I Can Help You Source</h2><p>Supplier, specification, price, packing and export feasibility are confirmed for each inquiry.</p></div><button className="dark" onClick={()=>go("products")}>View All Chemical Products →</button></div><div className="ah-product-grid">{showcase.map((item,i)=>{const p=products.find(product=>product.cas===item.cas)||products[i];return <article key={item.cas} onClick={()=>p&&openProduct(p)}><img src={item.image} alt={`${item.label} chemical sourcing`} onError={e=>{e.currentTarget.src="/home-v4/products-photo.webp"}}/><div><h3>{item.label}</h3><small>CAS {item.cas}</small><p>{item.text}</p><span>›</span></div></article>})}</div></div></section>
  <section className="ah-section ah-chain"><div className="ah-shell"><div className="ah-section-title"><div><h2>Local Supply Connected to Export Execution</h2><p>I coordinate suitable regional supply with qualified operating resources for repacking, inspection, dangerous-goods documentation, customs declaration, vessel booking and logistics.</p></div><button className="dark" onClick={()=>go("export-support")}>Explore Chemical Export Support →</button></div><div className="ah-chain-grid">{[["/home-v4/hero-refinery.png","Chemical Supply","Sourcing from Shandong and nearby regions"],["/home-v4/products-photo.webp","Qualified Repacking","Export packing and labelling"],["/blog/chloroform-vietnam-inspection.webp","Inspection & DG Documents","Inspection, MSDS and dangerous-goods documentation"],["/home-v4/hero-drums-photo.webp","Customs Declaration","Customs clearance with qualified parties"],["/home-v4/cta-ship-photo.webp","Vessel Booking","Vessel booking and logistics coordination"]].map((x,i)=><article key={x[1]}><img src={x[0]} alt=""/><h3>{x[1]}</h3><p>{x[2]}</p>{i<4&&<i>→</i>}</article>)}</div><div className="ah-boundary"><span/>Manufacturer, contracting exporter and licensed operating parties are confirmed for each transaction.<span/></div></div></section>
  <section className="ah-guides"><div className="ah-shell"><b>Latest Buyer Guides</b>{guides.map(a=><button key={a.slug} onClick={()=>onOpenArticle(a.slug)}>▤ &nbsp;{safe(a.title,lang)} →</button>)}<button onClick={()=>go("insights")}>View All Insights →</button></div></section>
  <section className="ah-contact"><div className="ah-shell ah-contact-grid"><article className="ah-person"><div className="ah-photo"><span>Your Real Photo</span></div><div><small>YOUR LOCAL POINT OF COORDINATION</small><h2>Your Name</h2><p>I remain your direct point of contact from requirement review and price confirmation through export preparation and shipment coordination.</p><b>Independent Chemical Sourcing &amp; Export Coordinator</b><em>Shandong, China</em><div className="ah-contact-actions"><a href="https://wa.me/8618678695200">◉ &nbsp; Chat on WhatsApp</a><a href="mailto:18678695200@163.com">✉ &nbsp; Email Me</a></div></div></article><form onSubmit={submit}><h2>Send Your Sourcing Requirement</h2><div className="ah-form-grid"><label>Product<input name="product" required placeholder="e.g. Xylene"/></label><label>CAS or Specification<input name="message" placeholder="e.g. 1330-20-7 or purity, grade"/></label><label>Quantity &amp; Packing<input name="quantity" required placeholder="e.g. 20 MT, drums or ISO tank"/></label><label>Destination Port<input name="destination" required placeholder="e.g. Singapore"/></label><label className="wide">Email<input type="email" name="email" required placeholder="name@company.com"/></label></div><button type="submit">Request a Supply &amp; Export Review →</button>{status&&<p className="ah-status">{status}</p>}</form></div></section>
  <footer className="ah-footer"><div className="ah-shell"><div className="ah-footer-row"><div className="ah-brand light"><b>ChinaChemExport</b><small>Independent Chemical Sourcing &amp; Export Coordinator</small></div><nav>{c.nav.slice(0,8).map((n,i)=><button key={`${n}-${i}`} onClick={()=>go(routes[i])}>{n}</button>)}</nav><div className="ah-social">◉　✉　in</div></div><div className="ah-footer-bottom"><p>ChinaChemExport is an independently operated sourcing and coordination service. Manufacturer, contracting exporter and licensed operating parties are confirmed for each transaction.</p><span>© 2026 ChinaChemExport. All rights reserved.</span></div></div></footer>
 </main>
}
