import { useState } from "react";
import type { FormEvent } from "react";
import type { Article, Lang, Page, Product } from "./HomePage";
import { productSlug } from "./productDetails";
import "./HomePageApproved.css";

type Props={go:(page:Page)=>void;lang:Lang;setLang:(lang:Lang)=>void;products:Product[];articles:Article[];onOpenArticle:(slug:string)=>void};
const copy={
  en:{nav:["Home","Chemical Sourcing","Export Support","Products","Insights","Contact"],hero:"China Chemical Sourcing & Export Support",intro:"Work directly with an independent coordinator connected to Shandong’s petrochemical supply base and qualified resources for repacking, inspection, DG documentation, customs and shipping.",based:"Based in Shandong, China · Supporting international industrial buyers"},
  zh:{nav:["首页","化工品寻源","出口支持","产品","行业洞察","联系"],hero:"中国化工品寻源与出口支持",intro:"直接对接立足山东的独立协调人，连接石化产业带货源，以及分装、检验、危包单证、报关和订舱等合格服务资源。",based:"立足中国山东 · 服务国际工业采购商"}
};
const routes:Page[]=["home","chemical-sourcing","export-support","products","insights","contact"];
const safe=(v:{en:string;zh:string},lang:Lang)=>v?.[lang]||v?.en||"";
const showcase=[
 {label:"Xylene",cas:"1330-20-7",image:"/home-v5/xylene.webp",text:"Solvent sourcing, specification and drum or ISO tank review."},
 {label:"Methylene Chloride",cas:"75-09-2",image:"/home-v5/methylene-chloride.webp",text:"Supplier, COA, MSDS, packing and DG shipment review."},
 {label:"Chloroform",cas:"67-66-3",image:"/home-v5/chloroform.webp",text:"Industrial-use, destination and export eligibility review."},
 {label:"Aniline",cas:"62-53-3",image:"/home-v5/aniline.webp",text:"Specification, packing and DG export coordination."},
 {label:"Dimethyl Carbonate",cas:"616-38-6",image:"/home-v5/dimethyl-carbonate.webp",text:"Grade, application and shipment-option confirmation."},
 {label:"Acetone",cas:"67-64-1",image:"/home-v5/acetone.webp",text:"Industrial packing and export-document review."}
];
function openProduct(p:Product){history.pushState({},"",`/products/${productSlug(p)}`);dispatchEvent(new PopStateEvent("popstate"));scrollTo({top:0,behavior:"smooth"})}
const Icon=({children}:{children:string})=><span className="ah-icon" aria-hidden="true">{children}</span>;

export default function HomePageApproved({go,lang,setLang,products,articles,onOpenArticle}:Props){
 const [menu,setMenu]=useState(false);const [status,setStatus]=useState("");const c=copy[lang];
 const guides=articles.slice(0,3);
 const bi=(en:string,zh:string)=>lang==="zh"?zh:en;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus(lang==="zh"?"正在提交…":"Sending…");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch("/api/inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error();setStatus(lang==="zh"?"已收到需求，我会直接回复。":"Requirement received. I will reply directly.");form.reset()}catch{setStatus(lang==="zh"?"暂时无法提交，请使用邮件或 WhatsApp。":"Unable to send. Please use email or WhatsApp.")}}
 return <main className="approved-home">
  <header className="ah-header"><div className="ah-shell ah-header-inner"><button className="ah-brand" onClick={()=>go("home")}><b>ChinaChemExport</b><small>{bi("Independent Chemical Sourcing & Export Coordinator","独立化工品寻源与出口协调服务")}</small></button><button className="ah-menu" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""}>{c.nav.map((n,i)=><button className={i===0?"active":""} key={`${n}-${i}`} onClick={()=>go(routes[i])}>{n}</button>)}<button className="ah-lang" aria-label={bi("Switch to Chinese","切换到英文")} onClick={()=>setLang(lang==="en"?"zh":"en")}>◉ {lang==="en"?"EN | 中文":"中文 | EN"}</button><button className="ah-top-cta" onClick={()=>go("contact")}>{lang==="zh"?"沟通采购需求":"Discuss Your Requirement"} →</button></nav></div></header>
  <section className="ah-hero"><div className="ah-hero-bg"/><div className="ah-shell ah-hero-content"><div><h1>{c.hero}</h1><p>{c.intro}</p><strong>{c.based}</strong><div className="ah-actions"><button className="primary" onClick={()=>go("contact")}>{lang==="zh"?"沟通采购需求":"Discuss Your Requirement"} →</button><button className="secondary" onClick={()=>go("export-support")}>{lang==="zh"?"了解寻源流程":"How Sourcing Works"}</button></div></div><div className="ah-hero-route" aria-hidden="true"><span>▧<small>Repacking<br/>&amp; Inspection</small></span><i>›</i><span>▤<small>DG Documents</small></span><i>›</i><span>♟<small>Customs<br/>Declaration</small></span><i>›</i><span>▰<small>Vessel Booking<br/>&amp; Shipping</small></span></div></div></section>
  <section className="ah-capabilities"><div className="ah-shell ah-cap-grid">{(lang==="zh"?[["▥","区域化工供应","连接山东及周边地区的中国化工品供应资源。","chemical-sourcing"],["●","多方案寻源比选","按规格和价格核验多个合适供应方案。","chemical-sourcing"],["◇","合格分装支持","通过具备相应条件的本地资源协调出口包装与标签。","export-support"],["▰","出口流程协调","通过合格服务方协调报关、订舱及出运跟进。","export-support"]]:[["▥","Regional Chemical Supply","Access to Chinese chemical suppliers in Shandong and nearby regions.","chemical-sourcing"],["●","Competitive Sourcing Options","Multiple qualified suppliers for specification and price confirmation.","chemical-sourcing"],["◇","Qualified Repacking Support","Export packing and labelling arranged through qualified local resources.","export-support"],["▰","Export Process Coordination","Customs declaration, vessel booking and shipment follow-up with approved providers.","export-support"]]).map(x=><article key={x[1]} role="link" tabIndex={0} onClick={()=>go(x[3] as Page)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go(x[3] as Page)}}}><Icon>{x[0]}</Icon><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="ah-section"><div className="ah-shell"><div className="ah-section-title"><div><h2>{bi("From Requirement to Shipment","从采购需求到完成出运")}</h2><p>{bi("I turn a buyer’s product requirement into a reviewed supply and export plan.","将采购需求转化为经过核验的供应与出口执行方案。")}</p></div><button onClick={()=>go("export-support")}>{bi("View the complete chemical export support process","查看完整化工品出口支持流程")} →</button></div><div className="ah-steps">{(lang==="zh"?[["1","▤","明确采购需求","产品、CAS、规格、数量、包装及目的地。"],["2","⌕","确认供应方案","核对供应商、当前供应、商务条款和批次文件。"],["3","◇","准备出口事项","协调合格分装、标签、检验和危包单证。"],["4","▰","协调完成出运","协调报关、订舱、危运及港口交付跟进。"]]:[["1","▤","Define Requirement","Product, CAS, specification, quantity, packing and destination."],["2","⌕","Confirm Supply Solution","Supplier, current availability, commercial terms and batch documents."],["3","◇","Prepare for Export","Qualified repacking, labels, inspection and DG packaging documents."],["4","▰","Coordinate Shipment","Customs declaration, vessel booking, DG transport and port follow-up."]]).map((x,i)=><article key={x[0]} role="link" tabIndex={0} onClick={()=>go("export-support")} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go("export-support")}}}><b>{x[0]}</b><Icon>{x[1]}</Icon><div><h3>{x[2]}</h3><p>{x[3]}</p></div>{i<3&&<i>›</i>}</article>)}</div></div></section>
  <section className="ah-section ah-products"><div className="ah-shell"><div className="ah-section-title"><div><h2>{bi("Selected Chemicals I Can Help You Source","可协助寻源的重点化工品")}</h2><p>{bi("Supplier, specification, price, packing and export feasibility are confirmed for each inquiry.","每次询盘均会核验供应商、规格、价格、包装及出口可行性。")}</p></div><button className="dark" onClick={()=>go("products")}>{bi("View All Chemical Products","查看全部化工产品")} →</button></div><div className="ah-product-grid">{showcase.map((item,i)=>{const p=products.find(product=>product.cas===item.cas)||products[i];return <article key={item.cas} role="link" tabIndex={0} onClick={()=>p&&openProduct(p)} onKeyDown={e=>{if(p&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openProduct(p)}}}><img src={item.image} alt={`${item.label} chemical sourcing`} onError={e=>{e.currentTarget.src="/home-v4/products-photo.webp"}}/><div><h3>{p?safe(p.name,lang):item.label}</h3><small>CAS {item.cas}</small><p>{lang==="zh"?"供应、规格、包装与出口条件按具体询盘确认。":item.text}</p><span>›</span></div></article>})}</div></div></section>
  <section className="ah-section ah-chain"><div className="ah-shell"><div className="ah-section-title"><div><h2>{bi("Local Supply Connected to Export Execution","连接本地供应与出口执行")}</h2><p>{bi("I coordinate suitable regional supply with qualified operating resources for repacking, inspection, dangerous-goods documentation, customs declaration, vessel booking and logistics.","协调合适的区域货源，并连接具备相应条件的分装、检验、危险品单证、报关、订舱和物流资源。")}</p></div><button className="dark" onClick={()=>go("export-support")}>{bi("Explore Chemical Export Support","了解化工品出口支持")} →</button></div><div className="ah-chain-grid">{(lang==="zh"?[["/home-v4/hero-refinery.png","化工品供应","山东及周边地区寻源"],["/home-v4/products-photo.webp","合格分装","出口包装与标签协调"],["/blog/chloroform-vietnam-inspection.webp","检验与危险品单证","检验、MSDS及危险品单证协调"],["/home-v4/hero-drums-photo.webp","报关协调","由合格主体完成通关操作"],["/home-v4/cta-ship-photo.webp","订舱出运","订舱与物流协调"]]:[["/home-v4/hero-refinery.png","Chemical Supply","Sourcing from Shandong and nearby regions"],["/home-v4/products-photo.webp","Qualified Repacking","Export packing and labelling"],["/blog/chloroform-vietnam-inspection.webp","Inspection & DG Documents","Inspection, MSDS and dangerous-goods documentation"],["/home-v4/hero-drums-photo.webp","Customs Declaration","Customs clearance with qualified parties"],["/home-v4/cta-ship-photo.webp","Vessel Booking","Vessel booking and logistics coordination"]]).map((x,i)=><article key={x[1]} role="link" tabIndex={0} onClick={()=>go("export-support")} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go("export-support")}}}><img src={x[0]} alt=""/><h3>{x[1]}</h3><p>{x[2]}</p>{i<4&&<i>→</i>}</article>)}</div><div className="ah-boundary"><span/>{bi("Manufacturer, contracting exporter and licensed operating parties are confirmed for each transaction.","生产商、签约出口主体及持证操作服务方均按具体交易确认。")}<span/></div></div></section>
  <section className="ah-guides"><div className="ah-shell"><b>{bi("Latest Buyer Guides","最新采购指南")}</b>{guides.map(a=><button key={a.slug} onClick={()=>onOpenArticle(a.slug)}>▤ &nbsp;{safe(a.title,lang)} →</button>)}<button onClick={()=>go("insights")}>{bi("View All Insights","查看全部洞察")} →</button></div></section>
  <section className="ah-contact"><div className="ah-shell ah-contact-grid"><article className="ah-person"><div className="ah-photo has-photo"><img src="/page-assets/chao-zhang-portrait.png" alt={bi("Chao Zhang, independent chemical sourcing and export coordinator in Shandong","张超，山东独立化工品寻源与出口协调人")}/></div><div><small>{bi("YOUR LOCAL POINT OF COORDINATION","您的本地协调联系人")}</small><h2>{bi("Work Directly with Chao Zhang","直接与张超沟通")}</h2><p>{bi("With years of hands-on experience in China’s domestic dangerous-chemical trade, I connect established Shandong supply channels with practical export coordination for overseas buyers.","我拥有多年国内危险化学品贸易实务经验，连接山东产业带供应渠道，并为海外买家协调切实可行的出口流程。")}</p><b>{bi("Independent Chemical Sourcing & Export Coordinator","独立化工品寻源与出口协调人")}</b><em>{bi("Chao Zhang · Shandong, China","张超 · 中国山东")}</em><div className="ah-experience-tags"><span>{bi("DG trade experience","危化品贸易经验")}</span><span>{bi("Regional supply access","区域供应链资源")}</span><span>{bi("Export process familiarity","熟悉出口流程")}</span></div><div className="ah-contact-actions"><a href="https://wa.me/8618678695200">◉ &nbsp; {bi("Chat on WhatsApp","WhatsApp 沟通")}</a><a href="mailto:18678695200@163.com">✉ &nbsp; {bi("Email Me","发送邮件")}</a></div></div></article><form onSubmit={submit}><h2>{bi("Send Your Sourcing Requirement","提交您的采购需求")}</h2><div className="ah-form-grid"><label>{bi("Product","产品名称")}<input name="product" required placeholder={bi("e.g. Xylene","例如：二甲苯")}/></label><label>{bi("CAS or Specification","CAS 或规格")}<input name="message" placeholder={bi("e.g. 1330-20-7 or purity, grade","例如：1330-20-7、纯度或等级")}/></label><label>{bi("Quantity & Packing","数量与包装")}<input name="quantity" required placeholder={bi("e.g. 20 MT, drums or ISO tank","例如：20 吨、桶装或 ISO Tank")}/></label><label>{bi("Destination Port","目的港")}<input name="destination" required placeholder={bi("e.g. Singapore","例如：新加坡")}/></label><label className="wide">{bi("Email","电子邮箱")}<input type="email" name="email" required placeholder="name@company.com"/></label></div><button type="submit">{bi("Request a Supply & Export Review","提交供应与出口评估")} →</button>{status&&<p className="ah-status">{status}</p>}</form></div></section>
  <footer className="ah-footer"><div className="ah-shell"><div className="ah-footer-row"><div className="ah-brand light"><b>ChinaChemExport</b><small>Independent Chemical Sourcing &amp; Export Coordinator</small></div><nav>{c.nav.slice(0,8).map((n,i)=><button key={`${n}-${i}`} onClick={()=>go(routes[i])}>{n}</button>)}</nav><div className="ah-social">◉　✉　in</div></div><div className="ah-footer-bottom"><p>ChinaChemExport is an independently operated sourcing and coordination service. Manufacturer, contracting exporter and licensed operating parties are confirmed for each transaction.</p><span>© 2026 ChinaChemExport. All rights reserved.</span></div></div></footer>
 </main>
}
